import type { NextPage } from 'next'
import Head from 'next/head'
import Draggable from '../components/Draggable'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>DAD</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Draggable>
                <div className='h-20 w-20 bg-red-800'></div>
            </Draggable>
            <Draggable>
                <div className='h-20 w-20 bg-blue-800'></div>
            </Draggable>
            <Draggable>
                <div className='h-20 w-20 bg-green-800'></div>
            </Draggable>
        </>
    )
}

export default Home
